version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: masareefi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:yourpassword@db:5432/masareefi

volumes:
  postgres_data:
